export const CATEGORIES = [
  "Akustik",
  "Alternatif",
  "Arabesk",
  "Bağımsız (Indie)",
  "Blues",
  "Caz (Jazz)",
  "Dans / EDM",
  "Dünya Müziği (World)",
  "Elektronik",
  "Enstrümantal",
  "Film / Soundtrack",
  "Folk",
  "Funk",
  "Halk Müziği",
  "Hip-Hop / Rap",
  "Klasik Müzik",
  "Latin",
  "Lo-Fi",
  "Metal",
  "Oyun Müziği",
  "Pop",
  "R&B / Soul",
  "Reggae",
  "Rock",
  "Sanat Müziği",
  "Sözlü Müzik",
  "Tasavvuf",
];

export const GENRES = [
  "Anadolu Rock",
  "Art Rock",
  "Bossa Nova",
  "Chillout",
  "Country",
  "Deep House",
  "Disco",
  "Doom Metal",
  "Dream Pop",
  "Dubstep",
  "Fantezi",
  "Flamenko",
  "Folk Rock",
  "Garage Rock",
  "Gospel",
  "Grunge",
  "Hard Rock",
  "Heavy Metal",
  "House",
  "Indie Pop",
  "Indie Rock",
  "K-Pop",
  "Kelt (Celtic)",
  "Latin Pop",
  "Neo-Soul",
  "New Age",
  "Nu Metal",
  "Pop Punk",
  "Pop Rock",
  "Post-Rock",
  "Progressive Rock",
  "Psychedelic Rock",
  "Punk Rock",
  "Reggaeton",
  "Shoegaze",
  "Ska",
  "Synthpop",
  "Techno",
  "Trance",
  "Trap",
  "Trip-Hop",
  "Türk Sanat Müziği",
  "Türk Halk Müziği",
  "Türkü",
];
